# run command ansible-playbook with --ask-become-pass
- hosts : atlantide
  remote_user: openfisca
  tasks:
    - name: Ensure environment is not activated
      lineinfile: dest=~/.bashrc line='. miniconda2/envs/OpenFisca/bin/activate OpenFisca' state=absent
    - name: Remove OpenFisca environment
      shell: conda remove --name OpenFisca --all -y
    - name: Create environment
      shell: conda create --name OpenFisca gunicorn numpy PyYAML requests Babel nose -y
    - name: Add env to bashrc path
      lineinfile: dest=~/.bashrc line='. miniconda2/envs/OpenFisca/bin/activate OpenFisca'
    - name: Install Biryani, conda doesn't have this package
      shell: pip install Biryani
      args:
        executable: /bin/bash
    - name: Install OpenFisca core
      shell: pip install -e git+https://github.com/openfisca/openfisca-core.git@master#egg=OpenFisca-Core
      args:
        executable: /bin/bash
    - name: Install OpenFisca france
      shell: pip install -e git+https://github.com/openfisca/openfisca-france.git@master#egg=OpenFisca-France
      args:
        executable: /bin/bash
    - name: Install OpenFisca Web API
      shell: pip install -e git+https://github.com/openfisca/openfisca-web-api.git@master#egg=OpenFisca-Web-API
      args:
        executable: /bin/bash
