# run command ansible-playbook with --ask-become-pass
- hosts : atlantide
  remote_user: openfisca
  tasks:
    - name: Ensure no environment is activated in bash
      lineinfile: dest=~/.bashrc regexp="miniconda2/envs" line='. miniconda2/envs/OpenFisca/bin/activate OpenFisca' state=absent
    - name: Remove OpenFisca environment
      shell: conda remove --name OpenFisca --all -y
    - name: Create environment
      shell: conda create --name OpenFisca gunicorn numpy scipy PyYAML requests Babel nose -y
    - name: Add env to bashrc path
      lineinfile: dest=~/.bashrc line='. miniconda2/envs/OpenFisca/bin/activate OpenFisca'
    - name: Install Biryani, conda doesn't have this package
      shell: pip install Biryani
